app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'], function () {
	Route::get('/', 'HomeController@index');
    Route::get('/home', 'GuestController@index');
    Route::auth();

    Route::get('auth/verify/{token}', 'Auth\RegisterController@verify');

    Route::get('/mail', 'HomeController@mail');

	Route::get('guest/{book}/borrow', [
		'middleware'=>['auth','role:member'],
		'as'=>'guest.books.borrow',
		'uses'=>'GuestController@borrow'
	]);

	Route::put('guest/{book}/return', [
		'middleware'=>['auth','role:member'],
		'as'=>'guest.books.return',
		'uses'=>'GuestController@returned'
	]);

	Route::get('settings/profile', 'SettingsController@profile');
	Route::get('settings/profile/edit','SettingsController@editProfile');
	Route::post('settings/profile','SettingsController@updateProfile');

	Route::get('settings/password', 'SettingsController@editPass');
	Route::post('settings/password', 'SettingsController@updatePass');

	Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
		Route::resource('authors', 'AuthorsController');
		Route::resource('books', 'BooksController');
		Route::resource('members', 'MemberController');
	});
});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Author;
use Session;

class Book extends Model
{
    public static function boot() {
    	parent::boot();

    	//mengecek perubahan amount buku tidak boleh kurang dari jumlah buku yang dipinjam
    	self::updating(function($book) {
	    	if($book->amount < $book->borrowed) {
	    		Session::flash("flash_notif", [
	    			"level" => "danger",
	    			"message" => "Jumlah buku $book->title harus >= $book->borrowed"
	    		]);
	    		return false;
	    	}
	    });

	    self::deleting(function($book) {
	    	if($book->borrowLogs() -> borrowed()) {
				Session::flash("flash_notif", [
					"level"=>"danger",
					"message"=>"Buku $book->title sedang dipinjam."
				]);
				return false;
	    	}	
	    });
    }

    protected $fillable = ['title', 'author_id', 'amount'];

    public function getBorrowedAttribute() {
    	return $this -> borrowLogs() -> borrowed()->count();
    }

    public function author() {
    	return $this -> belongsTo('App\Author'); 
    } 
 
	public function borrowLogs() {
		return $this->hasMany('App\BorrowLog');
	}
 
    public function getStokAttribute() {
		$borrowed = $this->borrowLogs()->borrowed()->count();
		$stock = $this->amount - $borrowed;
		return $stock;
    }

}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\StoreBookRequest;
use App\Http\Requests\UpdateBookRequest;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use App\Exceptions\BookException;
use App\Book;
use App\BorrowLog;
use Input;
use Session;
use Validator; 
use File;
 
class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Builder $htmlBuilder)
    {
        if($request -> ajax()) {
            $books = Book::with('author');
            return Datatables::of($books) -> addColumn('action2', function($book){
                return view('datatable.action', [
                    'model'    => $book, 
                    'edit_url' => route('admin.books.edit', $book->id),    
                    'delete_url' => route('admin.books.destroy', $book->id),
                    'confirm_message' => 'Yakin mau menghapus ' . $book->title . '?',
                ]);
            }) -> make(true);
        }

        $html = $htmlBuilder -> addColumn(['data' => 'title', 'name'=>'title', 'title' => 'Judul'])
            -> addColumn(['data' => 'amount', 'name'=>'amount','title'=>'Jumlah'])
            -> addColumn(['data'=>'author.name', 'name'=>'author.name', 'title'=>'Penulis'])
            -> addColumn(['data' => 'action2', 'name'=>'action2','title'=>'','orderable'=>false,'searchable'=>false]);

        return view('books.index')->with(compact('html'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookRequest $request)
    {
        /*
        $rules = [
            'title' => 'required|unique:books,title',
            'author_id' => 'required|exists:authors,id',
            'amount' => 'required|numeric',
            'cover' => 'required|image'
        ];

        $messages = [
            'required' => 'Field harus di isi alias tidak boleh kosong',
            'unique' => 'Nama '.$request -> title.' sudah ada dalam database.',
            'exists' => 'Author tidak ada dalam database',
            'numeric' => 'Isi field amount harus angka',
            'image' => 'Isi field cover harus image',
            'max' => 'Image tidak boleh lebih dari 2 mb'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            return redirect() -> route('admin.books.create')
                            ->withErrors($validator)
                            ->withInput();
        }
        */

        $book = Book::create($request->except('cover'));

        //isi field cover jika ada cover yang diupload

        if ($request->hasFile('cover')) {
            // Mengambil file yang diupload
            $uploaded_cover = $request->file('cover');
            // mengambil extension file
            $extension = $uploaded_cover->getClientOriginalExtension();
            // membuat nama file random berikut extension
            $filename = md5(time()) . '.' . $extension;
            // menyimpan cover ke folder public/img
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';
            $uploaded_cover->move($destinationPath, $filename);
            // mengisi field cover di book dengan filename yang baru dibuat
            $book->cover = $filename;
            $book->save();
        }

        Session::flash('flash_notif', [
            "level" => "success",
            "message" => "Berhasil menyimpan $book->title kedalam database"
        ]);

        return redirect() -> route('admin.books.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $books = Book::find($id);
        return view('books.edit')-> with(compact('books'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBookRequest $request, $id)
    {
        /*
        $rules = [
            'title' => 'required|unique:books,title,'.$id,
            'author_id' => 'required|exists:authors,id',
            'amount' => 'required|numeric',
            'cover' => 'required'
        ];

        $messages = [
            'required' => 'Field harus di isi alias tidak boleh kosong',
            'unique' => 'Nama '.$request -> title.' sudah ada dalam database.',
            'exists' => 'Author tidak ada dalam database',
            'numeric' => 'Isi field amount harus angka',
            'image' => 'Isi field cover harus image'
        ];


        $validator = Validator::make($request -> all(), $rules, $messages);

        if($validator -> fails()) {
            return back()
                        -> withErrors($validator)
                        -> withInput();
        }
        */

        $book = Book::find($id);
        $oldbook = $book -> title;
        if(!$book->update($request->all())) return redirect()->back();

        if($request -> hasFile('cover')) {
            //mengambil cover yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_cover = $request -> file('cover');
            $extension = $uploaded_cover -> getClientOriginalExtension();

            //membuat nama file random dengan extension
            $filename = md5(time()). '.' .$extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';

            //memindahkan file ke folder public/img
            $uploaded_cover->move($destinationPath, $filename);

            // hapus cover lama, jika ada
            if ($book->cover) {
                $old_cover = $book->cover;
                $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                    . DIRECTORY_SEPARATOR . $book->cover;
                try {
                    File::delete($filepath);
                } 
                catch (FileNotFoundException $e) {
                    // File sudah dihapus/tidak ada
                }
            }

            //ganti field cover dengan cover baru
            $book->cover = $filename;
            $book -> save();
        }
        
        Session::flash('flash_notif', [
            "level" => "success",
            "message" => "Berhasil mengubah ".$oldbook." menjadi ".$request -> title
        ]);

        return redirect() -> route('admin.books.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);
        $oldbook = $book -> title;
        $cover = $book->cover;
        if(!$book->delete()) return redirect()->back();
        
        if($cover) {
            $oldcover = $book -> cover;
            $filepath = public_path() . DIRECTORY_SEPARATOR. 'img' . DIRECTORY_SEPARATOR . $book->cover;
            try{
                File::delete($filepath);
            }
            catch(FileNotFoundException $e) {
                //file sudah tidak ad
            }
        }

        Session::flash('flash_notif', [
            "level" => "success",
            "message" => "Berhasil menghapus ".$oldbook
        ]);

        return redirect() -> route('admin.books.index');
    }

}

resources/views/books/create.blade.php
@extends('layouts.app')
	@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ url('/admin/books') }}">Buku</a></li>
					<li class="active">Tambah Buku</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Tambah Buku</h2>
					</div>
					<div class="panel-body">
						{!! Form::open(['url' => route('admin.books.store'),
						'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
							@include('books.formcreate')
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
	@endsection

resources/views/books/edit.blade.php
@extends('layouts.app') 
	@section('content')
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="{{ url('/home') }}">Dashboard</a></li>
						<li><a href="{{ url('/admin/books') }}">Buku</a></li>
						<li class="active">Ubah Buku</li>
					</ul>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h2 class="panel-title">Ubah Buku</h2>
						</div>
						<div class="panel-body">
							{!! Form::model($books, ['url' => route('admin.books.update', $books->id),
							'method'=>'put', 'class'=>'form-horizontal']) !!}

							@include('books.formedit')

							{!! Form::close() !!}
						</div> 
					</div>
				</div>
			</div>
		</div>
	@endsection

resources/views/books/formcreate.blade.php
<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
{!! Form::label('title', 'Judul', ['class'=>'col-md-2 control-label']) !!}
<div class="col-md-4">
{!! Form::text('title', null, ['class'=>'form-control']) !!}
{!! $errors->first('title', '<p class="help-block">:message</p>') !!}
</div>
</div>

<div class="form-group {!! $errors->has('author_id') ? 'has-error' : '' !!}">
{!! Form::label('author_id', 'Penulis', ['class'=>'col-md-2 control-label']) !!}
<div class="col-md-4">
{!! Form::select('author_id', [''=>'']+App\Author::pluck('name','id')->all(), null, [
	'class'=>'js-selectize',
	'placeholder' => 'Pilih Penulis Yuk']) !!}
{!! $errors->first('author_id', '<p class="help-block">:message</p>') !!}
</div>
</div>

<div class="form-group{{ $errors->has('amount') ? ' has-error' : '' }}">
{!! Form::label('amount', 'Jumlah', ['class'=>'col-md-2 control-label']) !!}
<div class="col-md-4">
{!! Form::number('amount', null, ['class'=>'form-control', 'min'=>1]) !!}
{!! $errors->first('amount', '<p class="help-block">:message</p>') !!}
</div>
</div>

<div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}">
{!! Form::label('cover', 'Cover', ['class'=>'col-md-2 control-label']) !!}
<div class="col-md-4">
{!! Form::file('cover') !!}
{!! $errors->first('cover', '<p class="help-block">:message</p>') !!}
</div>
</div>

<div class="form-group">
<div class="col-md-4 col-md-offset-2">
{!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
</div>
</div>

resources/views/books/formedit.blade.php
<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
{!! Form::label('title', 'Judul', ['class'=>'col-md-2 control-label']) !!}
<div class="col-md-4">
{!! Form::text('title', null, ['class'=>'form-control']) !!}
{!! $errors->first('title', '<p class="help-block">:message</p>') !!}
</div>
</div>

<div class="form-group {!! $errors->has('author_id') ? 'has-error' : '' !!}">
{!! Form::label('author_id', 'Penulis', ['class'=>'col-md-2 control-label']) !!}
<div class="col-md-4">
{!! Form::select('author_id', [''=>'']+App\Author::lists('name','id')->all(), null,[
	'class'=>'js-selectize',
	'placeholder' => 'Pilih Penulis'
]) !!}
{!! $errors->first('author_id', '<p class="help-block">:message</p>') !!}
</div>
</div>

<div class="form-group{{ $errors->has('amount') ? ' has-error' : '' }}">
	{!! Form::label('amount', 'Jumlah', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::number('amount', null, ['class'=>'form-control', 'min'=>1]) !!}
		{!! $errors->first('amount', '<p class="help-block">:message</p>') !!}
		@if(isset($books))
			<p class="help-block">{{ $books->borrowed }} buku sedang dipinjam </p>
		@endif
	</div>
</div>

<div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}">
	{!! Form::label('cover', 'Cover', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::file('cover') !!}
		@if (isset($books) && $books->cover)
			<p>
			{!! Html::image(asset('img/'.$books->cover), null, ['class'=>'img-rounded img-responsive']) !!}
			</p>
		@endif
		{!! $errors->first('cover', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group">
	<div class="col-md-4 col-md-offset-2">
	{!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
	</div>
</div>

resources/views/books/index.blade.php
@extends('layouts.app')

	@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="active">Buku</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Buku</h2>
					</div>
					<div class="panel-body">
						<p><a class="btn btn-primary" href="{{ url('/admin/books/create') }}">Tambah</a> </p>
					
						{!! $html -> table(['class' => 'table-striped']) !!}

					</div>
				</div>
			</div>
		</div>
	</div>
	@endsection

@section('scripts')
	{!! $html -> scripts() !!}
@endsection