app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'], function () {
	Route::get('/', 'HomeController@index');
    Route::get('/home', 'GuestController@index');
    Route::auth();

    Route::get('auth/verify/{token}', 'Auth\RegisterController@verify');

    Route::get('/mail', 'HomeController@mail');

	Route::get('guest/{book}/borrow', [
		'middleware'=>['auth','role:member'],
		'as'=>'guest.books.borrow',
		'uses'=>'GuestController@borrow'
	]);

	Route::put('guest/{book}/return', [
		'middleware'=>['auth','role:member'],
		'as'=>'guest.books.return',
		'uses'=>'GuestController@returned'
	]);

	Route::get('settings/profile', 'SettingsController@profile');
	Route::get('settings/profile/edit','SettingsController@editProfile');
	Route::post('settings/profile','SettingsController@updateProfile');

	Route::get('settings/password', 'SettingsController@editPass');
	Route::post('settings/password', 'SettingsController@updatePass');

	Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
		Route::resource('authors', 'AuthorsController');
		Route::resource('books', 'BooksController');
		Route::resource('members', 'MemberController');
	});
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <link href="{{ asset('css/font-awesome.min.css') }}" rel='stylesheet' type='text/css'>
    <link href="{{ asset('css/bootstrap.min.css') }}" rel='stylesheet' type='text/css'>
    <link href="{{ asset('css/jquery.dataTables.css') }}" rel = "stylesheet">
    <link href="{{ asset('css/dataTables.bootstrap.css') }}" rel="stylesheet" >
    <link href="{{ asset('css/selectize.css') }}" rel="stylesheet">
    <link href="{{ asset('css/selectize.bootstrap3.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel='stylesheet' type='text/css'>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    i-Library
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Daftar Buku</a></li>
                    @role('admin')
                    <li><a href="{{ route('admin.authors.index') }}">Penulis</a></li>
                    <li><a href="{{ route('admin.books.index') }}">Buku</a></li>
                    <li><a href="{{ route('admin.members.index') }}">Member</a></li>
                    @endrole
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Daftar</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                @if(auth()->check())
                                <li><a href="{{ url('/settings/profile') }}">Profile</a></li>
                                <li><a href="{{ url('/settings/password') }}">Change Password</a></li>
                                @endif
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @include('layouts.flash')
    
    @yield('content')

    <!-- JavaScripts -->
    <script src="{{ asset('js/jquery-3.1.0.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/selectize.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('scripts')
</body>
</html>

resources/views/layouts/flash.blade.php
@if (session()->has('flash_notif.message'))
	<div class="container">
		<div class="alert alert-{{ session()->get('flash_notif.level') }}">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		{!! session()->get('flash_notif.message') !!}
		</div>
	</div>
@endif